import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { ForgeConfig } from '@electron-forge/shared-types'
import { MakerDMG } from '@electron-forge/maker-dmg'
import { MakerDeb } from '@electron-forge/maker-deb'
import { MakerRpm } from '@electron-forge/maker-rpm'
import { MakerZIP } from '@electron-forge/maker-zip'
import { MakerSquirrel } from '@electron-forge/maker-squirrel'
import { AutoUnpackNativesPlugin } from '@electron-forge/plugin-auto-unpack-natives'
import { PublisherGithub } from '@electron-forge/publisher-github'

// macOS signing is opt-in via env: a release runner sets APPLE_SIGNING_IDENTITY
// (the exact "Developer ID Application: ... (TEAMID)" string) plus the three
// notarytool credentials. Local builds and CI without the cert produce an
// unsigned .app, which is correct for forks and PR builds.
const macSigning = process.env['APPLE_SIGNING_IDENTITY']
  ? {
      osxSign: {
        identity: process.env['APPLE_SIGNING_IDENTITY'],
        optionsForFile: () => ({
          hardenedRuntime: true,
          entitlements: 'resources/entitlements.mac.plist',
          'entitlements-inherit': 'resources/entitlements.mac.plist',
          'signature-flags': 'library',
        }),
      },
      ...(process.env['APPLE_API_KEY']
        ? {
            osxNotarize: {
              appleApiKey: process.env['APPLE_API_KEY'],
              appleApiKeyId: process.env['APPLE_API_KEY_ID']!,
              appleApiIssuer: process.env['APPLE_API_ISSUER']!,
            },
          }
        : {}),
    }
  : {}

// The GitHub repository that hosts releases. Also used for the update config
// written below, so the publisher and the updater can never disagree.
const UPDATE_REPO = { owner: 'maydali28', name: 'claudewatch' }

/**
 * electron-updater reads `path.join(process.resourcesPath, 'app-update.yml')`
 * in a packaged app, and refuses to download without it.
 *
 * That file is generated by electron-builder. We package with electron-forge,
 * which does not produce it, so it has never existed in any build. The update
 * *check* worked because `setFeedURL()` configures the provider in memory and
 * never consults the file, which is why this stayed hidden until someone
 * pressed Download and got:
 *
 *   ENOENT: no such file or directory, open
 *   '/Applications/ClaudeWatch.app/Contents/Resources/app-update.yml'
 *
 * `updaterCacheDirName` in particular is required — electron-updater logs
 * "updaterCacheDirName is not specified in app-update.yml" without it.
 *
 * packageAfterCopy runs with buildPath pointing at `<resources>/app`, before
 * the directory is packed into app.asar, so the file lands beside the asar in
 * Resources on every platform.
 */
async function writeUpdateConfig(buildPath: string): Promise<void> {
  const resourcesDir = path.resolve(buildPath, '..')
  const lines = [
    'provider: github',
    `owner: ${UPDATE_REPO.owner}`,
    `repo: ${UPDATE_REPO.name}`,
    'updaterCacheDirName: claudewatch-updater',
    '',
  ]
  await writeFile(path.join(resourcesDir, 'app-update.yml'), lines.join('\n'), 'utf8')
}

const config: ForgeConfig = {
  hooks: {
    packageAfterCopy: async (_forgeConfig, buildPath) => {
      await writeUpdateConfig(buildPath)
    },
  },
  // Forge outputs packaged artifacts to dist/ so it doesn't conflict with
  // electron-vite's build output in out/ (forge auto-ignores its own outDir).
  outDir: 'dist',
  packagerConfig: {
    name: 'ClaudeWatch',
    executableName: 'claudewatch',
    appBundleId: 'com.maydali.claudewatch',
    appCategoryType: 'public.app-category.developer-tools',
    icon: 'resources/icons/icon',
    asar: {
      unpack: '{node_modules/chokidar/**/*,node_modules/fsevents/**/*}',
    },
    ...macSigning,
    // Forge hardcodes ignore:[/^\/out\//g] but our electron-vite builds into out/.
    // Since we set outDir:'dist', forge no longer needs to exclude out/.
    //
    // Each entry below is one of: source we don't ship (src, scripts), build
    // outputs already represented elsewhere (dist), repo plumbing the user
    // doesn't need (.github, .husky, dotfiles), local docs/notes (TODO, *.md
    // at repo root), the lockfile (re-installs offline only need installed
    // node_modules), and packaging caches.
    //
    // Anything matched by a regex below is excluded from the .asar payload.
    // Audit `dist/Mac/ClaudeWatch.app/Contents/Resources/app.asar` after a
    // `pnpm package` to confirm — `npx asar list <path>` shows the contents.
    ignore: [
      /^\/src\//,
      /^\/dist\//,
      /^\/scripts\//,
      /^\/bundle\//,
      /^\/coverage\//,
      /^\/homebrew\//,
      /^\/patches\//,
      /^\/screenshots\//,
      /^\/sbom-scope\//,
      /^\/\.github\//,
      /^\/\.husky\//,
      /^\/\.vscode\//,
      /^\/node_modules\/\.cache\//,
      /^\/\./,
      /^\/electron\.vite/,
      /^\/forge\.config/,
      /^\/tsconfig.*\.json$/,
      /^\/eslint\.config/,
      /^\/vitest\.config/,
      /^\/changelog\.config/,
      /^\/audit-ci\.json$/,
      /^\/dependency-graph\.svg$/,
      /^\/pnpm-lock\.yaml$/,
      /^\/CHANGELOG\.md$/,
      /^\/README\.md$/,
      /^\/CONTRIBUTING\.md$/,
      /^\/CODE_OF_CONDUCT\.md$/,
      /^\/SECURITY\.md$/,
      /^\/TODO\.md$/i,
      /^\/production\.md$/i,
      /^\/THIRD_PARTY_LICENSES\.md$/,
    ],
  },
  makers: [
    // macOS: DMG installer (no auto-update — handled via Homebrew)
    new MakerDMG({
      format: 'ULFO',
    }),

    // Windows: Squirrel installer — produces Setup.exe + nupkg files consumed
    // by electron-updater's generic provider via latest.yml on the release server.
    new MakerSquirrel({
      name: 'claudewatch',
      setupExe: 'ClaudeWatch-Setup.exe',
      // Code-signing: set CSC_LINK + CSC_KEY_PASSWORD env vars in CI to sign.
      ...(process.env['CSC_LINK']
        ? {
            certificateFile: process.env['CSC_LINK'],
            certificatePassword: process.env['CSC_KEY_PASSWORD'],
          }
        : {}),
    }),

    // Linux: DEB and RPM packages consumed by electron-updater generic provider.
    new MakerDeb({
      options: {
        maintainer: 'may.mohamedali28@gmail.com',
        homepage: 'https://github.com/maydali28/claudewatch',
      },
    }),
    new MakerRpm({ options: {} }),

    // Portable ZIP for macOS (manual distribution) and Windows (fallback).
    new MakerZIP({}, ['darwin', 'win32']),
  ],
  plugins: [
    new AutoUnpackNativesPlugin({}),
  ],
  publishers: [
    new PublisherGithub({
      repository: UPDATE_REPO,
      prerelease: false,
      draft: true,
    }),
  ],
}

export default config
