import { describe, expect, it } from 'vitest'
import type { RawRecord } from '@shared/types/session'
import { classifyUserRecord } from './parser-helpers'

/**
 * Fixtures copy the shapes Claude Code writes today, read from a local
 * history in September 2026 (paths, ids and bodies redacted). The count
 * beside each shape is how many parent-transcript records of that shape the
 * probe found that month.
 */
function user(fields: Record<string, unknown>, content: unknown): RawRecord {
  return {
    type: 'user',
    uuid: 'u',
    timestamp: '2026-09-16T10:00:00.000Z',
    message: { role: 'user', content },
    ...fields,
  } as unknown as RawRecord
}

// 403 records: a prompt typed by a person.
const humanPrompt = user(
  { origin: { kind: 'human' }, promptSource: 'sdk' },
  'Plan the implementation of the blockers'
)

// 1 record: a skill slash command the person typed.
const humanSkillCommand = user(
  { origin: { kind: 'human' } },
  '<command-message>superpowers:writing-skills</command-message>\n<command-name>/superpowers:writing-skills</command-name>'
)

// 157 records: a background task finished.
const taskNotification = user(
  { origin: { kind: 'task-notification' }, promptSource: 'sdk' },
  '<task-notification>\n<task-id>a0</task-id>\n<status>completed</status>\n<summary>Agent "Research" finished</summary>\n</task-notification>'
)

// 22 records: a sub-agent handed its report back. `handback` sits on `origin`.
const handBack = user(
  {
    isMeta: true,
    origin: {
      kind: 'peer',
      from: 'a35e2511de91949d1',
      senderTaskId: 'a35e2511de91949d1',
      body: '[Subagent hand-back] …',
      handback: true,
    },
    promptSource: 'sdk',
  },
  'Another Claude session sent a message:\n<agent-message from="a35e2511de91949d1">\n[Subagent hand-back] The report follows:\n  # Report\n</agent-message>'
)

// 103 records: injected context such as a skill body.
const injectedSkillBody = user({ isMeta: true, sourceToolUseID: 'toolu_x' }, [
  { type: 'text', text: 'Base directory for this skill: <path>\n\n# Skill' },
])

// 7 records: the caveat that precedes local command output.
const localCommandCaveat = user(
  { isMeta: true },
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>'
)

// 7 records: a local slash command, never sent to the model.
const localCommand = user(
  {},
  '<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args>default</command-args>'
)

// 5 records: what a local command printed.
const localCommandStdout = user(
  {},
  '<local-command-stdout>Set model to `claude-opus-5[1m]`</local-command-stdout>'
)

// 7 records: the Esc interrupt marker.
const interrupt = user({}, [{ type: 'text', text: '[Request interrupted by user]' }])

// 4 records: compaction summary.
const compactSummary = user(
  { isCompactSummary: true, isVisibleInTranscriptOnly: true },
  'This session is being continued from a previous conversation that ran out of context.'
)

const toolResult = user({}, [{ type: 'tool_result', tool_use_id: 'toolu_1', content: 'ok' }])

describe('classifyUserRecord — one case per kind', () => {
  it.each([
    ['a prompt with a human origin', humanPrompt, 'prompt'],
    ['a tool_result carrier', toolResult, 'tool-result'],
    ['a compaction summary', compactSummary, 'compact-summary'],
    ['a background task notification', taskNotification, 'task-notification'],
    ['a sub-agent hand-back', handBack, 'agent-message'],
    ['an injected skill body', injectedSkillBody, 'meta'],
    ['a local command caveat', localCommandCaveat, 'local-command'],
    ['a local slash command', localCommand, 'local-command'],
    ['local command output', localCommandStdout, 'local-command'],
    ['an Esc interrupt marker', interrupt, 'interrupt'],
  ] as const)('classifies %s', (_label, raw, kind) => {
    expect(classifyUserRecord(raw)).toBe(kind)
  })
})

describe('classifyUserRecord — precedence', () => {
  it('keeps a skill command a person typed as a prompt', () => {
    expect(classifyUserRecord(humanSkillCommand)).toBe('prompt')
  })

  it('keeps a human-origin prompt that starts like a local command as a prompt', () => {
    expect(
      classifyUserRecord(
        user({ origin: { kind: 'human' } }, '<command-name>/review</command-name>')
      )
    ).toBe('prompt')
  })

  it('treats an isMeta record with a peer origin as an agent message, not meta', () => {
    expect(classifyUserRecord(handBack)).toBe('agent-message')
  })

  it('treats an unknown machine origin as meta', () => {
    // Sub-agent transcripts carry `origin.kind: 'coordinator'` for mid-task
    // messages from the parent agent.
    expect(
      classifyUserRecord(
        user({ isMeta: true, origin: { kind: 'coordinator' } }, 'The coordinator sent a message')
      )
    ).toBe('meta')
    expect(classifyUserRecord(user({ origin: { kind: 'something-new' } }, 'hello'))).toBe('meta')
  })

  it('classifies an old task notification with no origin by its text', () => {
    expect(
      classifyUserRecord(
        user({}, '\n<task-notification>\n<task-id>b1</task-id>\n</task-notification>')
      )
    ).toBe('task-notification')
  })

  it('classifies an old hand-back with no origin by its text', () => {
    expect(classifyUserRecord(user({}, 'Another Claude session sent a message:\nreport'))).toBe(
      'agent-message'
    )
    expect(
      classifyUserRecord(user({}, [{ type: 'text', text: 'note <agent-message from="x">hi' }]))
    ).toBe('agent-message')
  })

  it('keeps a plain prompt from an older writer with no origin as a prompt', () => {
    expect(classifyUserRecord(user({}, 'fix the failing test'))).toBe('prompt')
    expect(
      classifyUserRecord(
        user({}, [
          { type: 'image', source: {} },
          { type: 'text', text: 'what is in this screenshot?' },
        ])
      )
    ).toBe('prompt')
  })

  it('treats a tool_result carrier as a tool result even when it is marked meta', () => {
    expect(classifyUserRecord({ ...toolResult, isMeta: true })).toBe('tool-result')
  })

  it('treats a compaction summary as one even with a human origin', () => {
    expect(classifyUserRecord({ ...compactSummary, origin: { kind: 'human' } })).toBe(
      'compact-summary'
    )
  })

  it('treats a no-origin meta record as meta, not a prompt', () => {
    expect(classifyUserRecord(user({ isMeta: true }, 'an image caption'))).toBe('meta')
  })
})
