/**
 * Parses CHANGELOG.md (generated by `pnpm changelog` from conventional commits)
 * into version-keyed sections. The raw markdown body of each section is handed
 * to MarkdownRenderer in the What's New modal — no hand-curated highlights.
 *
 * Expected section shape produced by conventional-changelog:
 *   ## <version> (YYYY-MM-DD)
 *   ...body...
 */

// eslint-disable-next-line no-restricted-imports -- CHANGELOG.md lives at the repo root, outside any aliased package
import changelogSource from '../../../../CHANGELOG.md?raw'

export interface ChangelogEntry {
  version: string
  date: string
  body: string
}

const HEADING = /^##\s+\[?([^\s\]]+)\]?[^\n]*?\((\d{4}-\d{2}-\d{2})\)/gm

function parse(source: string): ChangelogEntry[] {
  const entries: ChangelogEntry[] = []
  const matches = [...source.matchAll(HEADING)]
  for (let i = 0; i < matches.length; i++) {
    const current = matches[i]
    const next = matches[i + 1]
    const start = current.index! + current[0].length
    const end = next ? next.index! : source.length
    entries.push({
      version: current[1],
      date: current[2],
      body: source.slice(start, end).trim(),
    })
  }
  return entries
}

export const CHANGELOG: ChangelogEntry[] = parse(changelogSource)

export function getLatestChangelog(): ChangelogEntry | null {
  return CHANGELOG[0] ?? null
}

export function getChangelogForVersion(version: string): ChangelogEntry | null {
  return CHANGELOG.find((e) => e.version === version) ?? null
}
